

- apt: name={{ item }} state=present
  with_items:
     - cifs-utils

- name: Mount datengrab read-write
  mount:
    name: /mnt/datengrab
    src: //datengrab.rzl/SHARE
    fstype: cifs
    opts: rw,uid=1000,gid=1000,guest
    state: mounted
