
- apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-php5
    - php-pear

- git: repo=http://git.joshuawise.com/git/patchfork.git
       dest=/var/www/html/mpd

- copy:
    src: config.xml
    dest: /var/www/html/mpd/config/config.xml